// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Submission struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	Email     string           `json:"email"`
	BirthDate string           `json:"birth_date"`
	Bio       string           `json:"bio"`
	Sex       int16            `json:"sex"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
}

type SubmissionLanguage struct {
	SubmissionID int32 `json:"submission_id"`
	LanguageID   int32 `json:"language_id"`
}
