// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID   int32
	Name string
}

type Submission struct {
	ID        int32
	Name      string
	Phone     string
	Email     string
	BirthDate pgtype.Date
	Bio       string
	Sex       int16
	CreatedAt pgtype.Timestamp
	Username  string
	Password  string
}

type SubmissionLanguage struct {
	SubmissionID int32
	LanguageID   int32
}
