// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getSubmissions = `-- name: GetSubmissions :many
select
  id, name, phone, email, birth_date, bio, sex, created_at, username, password
from
  submissions
`

func (q *Queries) GetSubmissions(ctx context.Context) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.BirthDate,
			&i.Bio,
			&i.Sex,
			&i.CreatedAt,
			&i.Username,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
